import type { ClueCandidate } from "./types";

/** Stormlight-themed fixture bank for packer / UI development without LLM. */
export const STORMIGHT_FIXTURE: ClueCandidate[] = [
  { answer: "KALADIN", clue: "Bridge Four leader and Windrunner" },
  { answer: "SHALLAN", clue: "Lightweaver who sketches what she sees" },
  { answer: "DALINAR", clue: "Highprince seeking to unite Alethkar" },
  { answer: "SZETH", clue: "Assassin in White" },
  { answer: "SPRREN", clue: "Typo trap — replaced below" },
  { answer: "SPREN", clue: "Spirits that bond with Radiants" },
  { answer: "STORMLIGHT", clue: "Glowing Investiture stored in gems" },
  { answer: "SHARDBLADE", clue: "Summoned weapon of a Knight Radiant" },
  { answer: "SHARDPLATE", clue: "Living armor of a Knight Radiant" },
  { answer: "WINDRUNNER", clue: "Order that rides the winds" },
  { answer: "LIGHTWEAVER", clue: "Order skilled in Illusion and Transformation" },
  { answer: "BONDSMITH", clue: "Order that Adhesion and Tension" },
  { answer: "EDGEDANCER", clue: "Order of Abrasion and Progression" },
  { answer: "SKYBREAKER", clue: "Order devoted to law and justice" },
  { answer: "DUSTBRINGER", clue: "Order of Division and Abrasion" },
  { answer: "TRUTHWATCHER", clue: "Order of Progression and Illumination" },
  { answer: "ELSECALLER", clue: "Order of Transformation and Transportation" },
  { answer: "WILLSHAPER", clue: "Order of Transportation and Cohesion" },
  { answer: "STONEWARD", clue: "Order of Cohesion and Tension" },
  { answer: "URITHIRU", clue: "Ancient tower city of the Radiants" },
  { answer: "ROSHAR", clue: "World battered by highstorms" },
  { answer: "HIGHSTORM", clue: "Powerful weather system that renews Stormlight" },
  { answer: "EVERSTORM", clue: "New storm that travels the wrong way" },
  { answer: "ODIUM", clue: "Shard of hatred opposing Honor" },
  { answer: "HONOR", clue: "Shard once held by the Almighty" },
  { answer: "CULTIVATION", clue: "Shard who shapes growth on Roshar" },
  { answer: "SYL", clue: "Kaladin's honorspren" },
  { answer: "PATTERN", clue: "Shallan's cryptic spren" },
  { answer: "IVORY", clue: "Jasnah's inkspren" },
  { answer: "ADOLIN", clue: "Duelist son of Dalinar" },
  { answer: "JASNAH", clue: "Scholar queen and Elsecaller" },
  { answer: "NAVAANI", clue: "Scholar and queen of Alethkar" },
  { answer: "BRIDGEFOUR", clue: "Kaladin's crew of bridgemen" },
  { answer: "PARSHENDI", clue: "Listeners who fought the Alethi" },
  { answer: "VOIDLIGHT", clue: "Investiture associated with Odium" },
  { answer: "LOPEN", clue: "Herdazian bridgeman with one arm" },
  { answer: "TEFT", clue: "Sergeant who helps rebuild Bridge Four" },
  { answer: "ROCK", clue: "Horn Eater cook of Bridge Four" },
  { answer: "MOASH", clue: "Bridgeman who turns against the Radiants" },
  { answer: "TARIEN", clue: "Typo — removed in normalize" },
  { answer: "TARAVANGIAN", clue: "King who gambles with Diagrams" },
  { answer: "DIAGRAM", clue: "Plan written in a day of brilliance" },
  { answer: "NIGHTBLOOD", clue: "Sentient black sword that hungers" },
  { answer: "AZIR", clue: "Empire known for bureaucracy" },
  { answer: "THAYLENAH", clue: "Island nation of merchants" },
  { answer: "HERDAZ", clue: "Nation of rocklike fingernails" },
  { answer: "SHINOVAR", clue: "Grass-covered land of the Shin" },
  { answer: "AIMIA", clue: "Shattered island of ancient secrets" },
  { answer: "KHOLODAR", clue: "Typo trap" },
  { answer: "KHOLODAR", clue: "duplicate trap" },
];

export const STORMIGHT_FIXTURE_CLEAN: ClueCandidate[] = [
  { answer: "KALADIN", clue: "Bridge Four leader and Windrunner" },
  { answer: "SHALLAN", clue: "Lightweaver who sketches what she sees" },
  { answer: "DALINAR", clue: "Highprince seeking to unite Alethkar" },
  { answer: "SZETH", clue: "Assassin in White" },
  { answer: "SPREN", clue: "Spirits that bond with Radiants" },
  { answer: "STORMLIGHT", clue: "Glowing Investiture stored in gems" },
  { answer: "SHARDBLADE", clue: "Summoned weapon of a Knight Radiant" },
  { answer: "SHARDPLATE", clue: "Living armor of a Knight Radiant" },
  { answer: "WINDRUNNER", clue: "Order that rides the winds" },
  { answer: "LIGHTWEAVER", clue: "Order skilled in Illusion" },
  { answer: "EDGEDANCER", clue: "Order of Abrasion and Progression" },
  { answer: "SKYBREAKER", clue: "Order devoted to law" },
  { answer: "URITHIRU", clue: "Ancient tower city of the Radiants" },
  { answer: "ROSHAR", clue: "World battered by highstorms" },
  { answer: "HIGHSTORM", clue: "Weather that renews Stormlight" },
  { answer: "EVERSTORM", clue: "Storm that travels the wrong way" },
  { answer: "ODIUM", clue: "Shard of hatred" },
  { answer: "HONOR", clue: "Shard once held by the Almighty" },
  { answer: "CULTIVATION", clue: "Shard who shapes growth" },
  { answer: "SYL", clue: "Kaladin's honorspren" },
  { answer: "PATTERN", clue: "Shallan's cryptic spren" },
  { answer: "IVORY", clue: "Jasnah's inkspren" },
  { answer: "ADOLIN", clue: "Duelist son of Dalinar" },
  { answer: "JASNAH", clue: "Scholar queen and Elsecaller" },
  { answer: "NAVAANI", clue: "Scholar and queen of Alethkar" },
  { answer: "PARSHENDI", clue: "Listeners who fought the Alethi" },
  { answer: "VOIDLIGHT", clue: "Investiture associated with Odium" },
  { answer: "LOPEN", clue: "Herdazian bridgeman" },
  { answer: "TEFT", clue: "Sergeant of Bridge Four" },
  { answer: "ROCK", clue: "Horn Eater cook" },
  { answer: "MOASH", clue: "Bridgeman turned antagonist" },
  { answer: "TARAVANGIAN", clue: "King behind the Diagram" },
  { answer: "DIAGRAM", clue: "Plan written in a day of brilliance" },
  { answer: "NIGHTBLOOD", clue: "Sentient black sword" },
  { answer: "AZIR", clue: "Empire known for bureaucracy" },
  { answer: "THAYLENAH", clue: "Island nation of merchants" },
  { answer: "HERDAZ", clue: "Nation of rocklike fingernails" },
  { answer: "SHINOVAR", clue: "Grass-covered land of the Shin" },
  { answer: "AIMIA", clue: "Shattered island of secrets" },
  { answer: "RADIANT", clue: "Knight bound to a spren" },
  { answer: "OATHS", clue: "Ideals a Radiant speaks" },
  { answer: "BRIDGE", clue: "What bridgemen carry into battle" },
  { answer: "SPEAR", clue: "Kaladin's preferred weapon" },
  { answer: "GLYPH", clue: "Symbolic writing of Vorin peoples" },
  { answer: "SPANREED", clue: "Paired pens for distant writing" },
  { answer: "FABRIAL", clue: "Device powered by trapped spren" },
  { answer: "CHULL", clue: "Large crustacean beast of burden" },
  { answer: "AXEHOUND", clue: "Domesticated crustacean companion" },
  { answer: "CREMLING", clue: "Small scavenging crustacean" },
  { answer: "LASHING", clue: "Windrunner ability that changes gravity" },
];
